apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: goktor
  namespace: test-ns
spec:
  destination:
    namespace: test-ns
    server: https://???
  project: default 
  source: 
    path: apps/bgd/overlays/bgd
    repoURL: https://github.com/redhat-developer-demos/openshift-gitops-examples
    targetRevision: minikube
  syncPolicy: 
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true